name: Backend Tests (Maven)

on:
  push:
    branches: [ dev, main, "feature/**", "test/**" ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Make mvnw executable
        run: chmod +x mvnw

      # Lance tests + JaCoCo (report à la phase verify)
      - name: Test & Coverage
        run: ./mvnw -B -ntp clean verify -Dspring.profiles.active=test

      # Toujours uploader les rapports de tests (même en cas d'échec)
      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: backend/target/surefire-reports

      - name: Upload JaCoCo Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: backend/target/site/jacoco
