name: Backend Tests (Maven)

on:
  push:
    branches: [ dev, main, "feature/**", "test/**" ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'
      - run: ./mvnw -q -Dspring.profiles.active=test test
      - run: ./mvnw -q jacoco:report
      - uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: backend/target/site/jacoco
